spring:
  profiles:
    active: default
  application:
    name: gateway-proxy
  redis:
    host: 192.168.125.128
    port: 6379
    database: 0
server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: house-service
          uri: lb://HOUSE-SERVICE
          predicates:
            - Path=/api/house/**
          filters:
            #去掉前缀的个数
            - StripPrefix=1
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/pic/**
#          filters:
#            #去掉前缀的个数
#            - StripPrefix=1
  profiles: default

#---
#spring:
#  application:
#    name: gateway-server
#  cloud:
#    gateway:
#      routes:
#        - id: service-consumer
#          uri: lb://SERVICE-CONSUMER
#          predicates:
#            - Path=/api/consumer/**
#          filters:
#            #去掉前缀的个数
#            - StripPrefix=1
#            - name: RequestRateLimiter
#              args:
#                key-resolver: '#{@hostAddrKeyResolver}'
#                redis-rate-limiter.replenishRate: 2
#                redis-rate-limiter.burstCapacity: 10
#        - id: service-producer
#          uri: lb://SERVICE-PRODUCER
#          predicates:
#            - Path=/api/producer/**
#          filters:
#            #去掉前缀的个数
#            - StripPrefix=1
#  profiles: host_route